# -*- coding: utf-8 -*-
"""credit card fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9bbDIe50yvcRG8UILhjYP0Nv2XNcf1O
"""

import pandas as pd
import numpy as np
import seaborn as sns

df=pd.read_csv('/content/credit_card_fraud_10k.csv')
df.head()

df.info()

df.describe()

df.isna().sum()

df.duplicated().sum()

df.dtypes

# Dataset is highly imbalanced (~98.5% normal, ~1.5% fraud).
# Accuracy is misleading — focus on Precision, Recall, F1.
# Use class weights or SMOTE to handle imbalance.
df['is_fraud'].value_counts()
df['is_fraud'].value_counts(normalize=True)

# Transactions above the 95th percentile are rare high-value cases
# Transactions above the 99th percentile are extreme outliers
df['amount'].quantile([0.95, 0.99])

df.groupby('is_fraud')['amount'].mean()
df.groupby('is_fraud')['velocity_last_24h'].mean()

#EDA fraud vs non-fraud

#Compare mean amount
df.groupby('is_fraud')['amount'].mean()

#Compare velocity
df.groupby('is_fraud')['velocity_last_24h'].mean()

df.groupby(['transaction_hour','is_fraud']).size().unstack(fill_value=0)
# Fraud transactions are higher during late night hours (0–2),
# indicating increased risk during midnight period.

# Most frequent merchant category for each class (fraud vs normal)
df.groupby('is_fraud')['merchant_category'].agg(lambda x: x.mode()[0])

# EDA for fraud rates
# Overall fraud rate
df['is_fraud'].mean()

df.groupby('merchant_category')['is_fraud'].mean().sort_values(ascending=False)

df.groupby('transaction_hour')['is_fraud'].mean().sort_values(ascending=False)

df.groupby('foreign_transaction')['is_fraud'].mean()

df.groupby('location_mismatch')['is_fraud'].mean()

df.groupby('velocity_last_24h')['is_fraud'].mean()

# Feature engineering
# High amoount flag (95th percentile)
threshold = df['amount'].quantile(0.95)
df['high_amount_flag'] = (df['amount'] > threshold).astype(int)

# Night Transaction Flag (0–5 AM)
df['night_transaction_flag'] = (df['transaction_hour'].between(0,5)).astype(int)

# Low Device Trust Flag (<30)
df['low_trust_flag'] = (df['device_trust_score'] < 30).astype(int)

df.head(2)

# High amoount flag (95th percentile) fraud rate
df.groupby('high_amount_flag')['is_fraud'].mean()

# Night Transaction Flag (0–5 AM)
df.groupby('night_transaction_flag')['is_fraud'].mean()

# Low Device Trust Flag (<30)
df.groupby('low_trust_flag')['is_fraud'].mean()

from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', sparse_output=False)

encoded = encoder.fit_transform(df[['merchant_category']])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['merchant_category'])
)

df = pd.concat([df.drop('merchant_category', axis=1), encoded_df], axis=1)

from sklearn.model_selection import train_test_split

# Train-test split = dividing data into two parts:
# Train set → model learns patterns
# Test set → model is evaluated on unseen data
# Usually 80% train, 20% test.

X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# class_weight='balanced' gives more importance to minority class (fraud)
# It penalizes wrong fraud predictions more to handle class imbalance

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced', max_iter=5000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_prob)